from pathlib import Path

GENE_FILE_MAP = {
    "12s": ["iguacu12s_1.fasta", "iguacu12s_2.fasta", "iguacu12s_3.fasta"],
    "16s": ["iguacu16s_1.fasta", "iguacu16s_2.fasta", "iguacu16s_3.fasta"],
    "COI": ["iguacuCOI_1.fasta", "iguacuCOI_2.fasta", "iguacuCOI_3.fasta", "iguacuCOI_4.fasta", "iguacuCOI_5.fasta", "iguacuCOI_6.fasta", "iguacuCOI_7.fasta", "iguacuCOI_8.fasta"]
}

PROJECT_ROOT = Path(__file__).resolve().parent.parent
DATA_FOLDER = PROJECT_ROOT / "data"
RAW_FOLDER = DATA_FOLDER / "raw"
INTERIM_FOLDER = DATA_FOLDER / "interim"
FINAL_FOLDER = DATA_FOLDER / "final"
FASTA_FOLDER = PROJECT_ROOT / RAW_FOLDER / "fasta"
VALID_NAMES = RAW_FOLDER / "valid_names.csv"
ACCESSION_GENE_CSV = INTERIM_FOLDER / "accession_gene.csv"
GENBANK_RECORDS = INTERIM_FOLDER / "genbank_records.gb"
PARSED_GB_RECS = INTERIM_FOLDER / "parsed_gb_recs.csv"
RECONCILED_TAXONOMY = INTERIM_FOLDER / "reconciled_taxonomy.csv"
REVISIT_RECS = INTERIM_FOLDER / "revisit_recs.csv"
RELIABILITY_CLASS = FINAL_FOLDER / "reliability_class.csv"
SUMMARY = FINAL_FOLDER / "summary.xlsx"
EXPECTED_QUALIFIERS = ["collection_date", "isolate", "db_xref", "geo_loc_name", "lat_lon", "specimen_voucher"]
ADDRESSES = INTERIM_FOLDER / "addresses.csv"

LOCATIONS = {
    "countries": ['brasil', 'brazil', 'br'],
    "states": ['parana'],
    "cities": [
        "curitiba",
        "foz do iguacu",
        "lindoeste",
        "mallet",
        "mangueirinha",
        "marmeleiro",
        "marquinho",
        "passos maia",
        "palmas",
        "matos costa",
        "jupia",
        "sao lourenco do oeste",
        "itapejara doeste",
        "palmeira",
        "salgado filho",
        "morretes",
        "pato branco",
        "reboucas",
        "renascenca",
        "rio branco do sul",
        "santo antonio do sudoeste",
        "sao joao do triunfo",
        "sao jose dos pinhais",
        "saudade do iguacu",
        "tres barras do parana",
        "monte castelo",
        "uniao da vitoria",
        "mafra",
        "guarapuava",
        "guaraniaçu",
        "campo largo",
        "barracao",
        "capanema",
        "rio do campo",
        "jose boiteux",
        "macieira",
        "almirante tamandare",
        "prudentopolis",
        "cruz machado",
        "dois vizinhos",
        "pinhais",
        "pinhal de sao bento",
        "salto do lontra",
        "turvo",
        "tijucas do sul",
        "pien",
        "bom jesus do sul",
        "campo alegre",
        "sao mateus do sul",
        "tres barras",
        "santa cecilia",
        "quitandinha",
        "chopinzinho",
        "reserva do iguacu",
        "guaratuba",
        "matelandia",
        "planalto",
        "sao domingos",
        "galvao",
        "major vieira",
        "rio negrinho",
        "timbo grande",
        "campo magro",
        "colombo",
        "quedas do iguacu",
        "sao miguel do iguacu",
        "catanduvas",
        "fernandes pinheiro",
        "ceu azul",
        "candoi",
        "porto amazonas",
        "porto barreiro",
        "cascavel",
        "perola doeste",
        "santa tereza do oeste",
        "joinville",
        "dionisio cerqueira",
        "clevelandia",
        "mariopolis",
        "cacador",
        "calmon",
        "general carneiro",
        "porto uniao",
        "abelardo luz",
        "papanduva",
        "serranopolis do iguacu",
        "rio azul",
        "capitao leonidas marques",
        "nova laranjeiras",
        "santa izabel do oeste",
        "santa lucia",
        "bela vista da caroba",
        "boa vista da aparecida",
        "mandirituba",
        "medianeira",
        "nova esperanca do sudoeste",
        "realeza",
        "rio bonito do iguacu",
        "sao joao",
        "palma sola",
        "irineopolis",
        "lebon regis",
        "diamante do sul",
        "rio negro",
        "araucaria",
        "itaiopolis",
        "sao jorge do oeste",
        "flor da serra do sul",
        "manfrinopolis",
        "agudos do sul",
        "sao bento do sul",
        "campo ere",
        "campina do simao",
        "campo bonito",
        "campina grande do sul",
        "campo do tenente",
        "cantagalo",
        "contenda",
        "coronel domingos soares",
        "coronel vivida",
        "eneas marques",
        "goioxim",
        "paulo frontin",
        "porto vitoria",
        "pranchita",
        "vera cruz do oeste",
        "vere",
        "virmond",
        "vitorino",
        "ampere",
        "antonio olinto",
        "balsa nova",
        "bituruna",
        "boa esperanca do iguacu",
        "bom sucesso do sul",
        "espigao alto do iguacu",
        "foz do jordao",
        "francisco beltrao",
        "honorio serpa",
        "ibema",
        "irati",
        "lapa",
        "laranjeiras do sul",
        "rio dos cedros",
        "doutor pedrinho",
        "corupa",
        "garuva",
        "agua doce",
        "pinhao",
        "piraquara",
        "quatro barras",
        "sulina",
        "canoinhas",
        "bela vista do toldo",
        "cruzeiro do iguacu",
        "fazenda rio grande",
        "inacio martins",
        "santa terezinha de itaipu",
        "nova prata do iguacu",
        "paula freitas"
        ],
    "rivers": ['iguacu', 'iguassu']
}
